version: '3.8'

services:
  # Dịch vụ 1: Database PostgreSQL
  db:
    image: postgres:15
    container_name: hotel_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hotel_management
    # ports:
    #   - "5432:5432"  <-- QUAN TRỌNG: Đóng port này lại để chặn Hack/Virus
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./hotel_management.sql:/docker-entrypoint-initdb.d/init.sql

  # Dịch vụ 2: Node.js Backend
  app:
    build: .
    container_name: hotel_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=hotel_management
      - DB_PORT=5432
      - PORT=3000
      - API_SECRET_KEY=my_secure_hotel_secret
    depends_on:
      - db

volumes:
  pgdata: